services:
  # Servicio para la base de datos PostgreSQL + pgvector
  db:
    image: pgvector/pgvector:pg16    
    restart: unless-stopped    
    volumes:
      - ./.storage/postgres-data:/var/lib/postgresql/data
      # Volumen para los scripts de inicialización
      - ./.files/postgres/00_starter.sql:/docker-entrypoint-initdb.d/00_starter.sql
    environment:
      - POSTGRES_USER=${DB_POSTGRES_USER}
      - POSTGRES_PASSWORD=${DB_POSTGRES_PASSWORD}
      - POSTGRES_DB=${DB_POSTGRES_DB}
      - POSTGRES_PORT=${DB_POSTGRES_PORT}
    ports:
      - "${DB_POSTGRES_PORT}:5432"

  # 1. Servidor de Langfuse (interfaz web y API)
  langfuse-server:
    image: langfuse/langfuse:3
    depends_on:
      - langfuse-db
      - clickhouse
    environment:
      - NODE_ENV=${LANGFUSE_NODE_ENV}
      - DATABASE_URL=${LANGFUSE_DATABASE_URL}
      - CLICKHOUSE_URL=${LANGFUSE_CLICKHOUSE_URL}
      - NEXTAUTH_SECRET=${LANGFUSE_NEXTAUTH_SECRET}
      - SALT=${LANGFUSE_SALT}
    ports:
      - "${LANGFUSE_PORT}:3000"

  # 2. Base de datos dedicada para Langfuse
  langfuse-db:
    image: postgres:15
    restart: unless-stopped
    volumes:      
      - ./.storage/langfuse-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${LANGFUSE_DB_USER}
      - POSTGRES_PASSWORD=${LANGFUSE_DB_PASSWORD}
      - POSTGRES_DB=${LANGFUSE_DB_NAME}
    ports:
      - "${POSTGRES_PORT}:5432"

  # 3. Base de datos ClickHouse para analíticas (NUEVO)
  clickhouse:
    image: clickhouse/clickhouse-server:25.8.10-alpine
    restart: unless-stopped
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./.storage/clickhouse-data:/var/lib/clickhouse
      - ./.storage/clickhouse-logs:/var/log/clickhouse-server
    environment:
      - CLICKHOUSE_DB=${CLICKHOUSE_DB}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
        