services:
  app:
    image: mcr.microsoft.com/devcontainers/python:1-3.12-bookworm
    command: sleep infinity
    volumes:
      - .:/workspace:cached 
    depends_on:
      - db
    networks:
      - app-network
  db:
    extends:
      file: ./docker-compose.yml
      service: db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Ab123456
      - POSTGRES_PORT=5432
      - POSTGRES_DB=vic_db
    ports:
      - "5433:5432"
    networks:
      - app-network
  
networks:
  app-network:
    driver: bridge