services:
  app:
    image: mcr.microsoft.com/devcontainers/python:1-3.12-bookworm
    command: sleep infinity
    volumes:
      - .:/workspace:cached 
    depends_on:
      - db
    networks:
      - app-network
  db:
    extends:
      file: ./docker-compose.yml
      service: db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Ab123456
      - POSTGRES_PORT=5432
      - POSTGRES_DB=vic_db
    ports:
      - "5433:5432"
    networks:
      - app-network
  langfuse-server:
    extends:
      file: ./docker-compose.yml
      service: langfuse-server
    environment:
      - NODE_ENV=production
      - NEXTAUTH_SECRET=Ab123456_NEXT
      - SALT=Ab123456_SALT
      - DATABASE_URL=postgresql://langfuse:Ab123456@langfuse-db:5432/langfuse
      - CLICKHOUSE_URL=http://langfuse:Ab123456@clickhouse:8123/langfuse
    ports:
      - "3001:3000"
    networks:
      - app-network
  langfuse-db:
    extends:
      file: ./docker-compose.yml
      service: langfuse-db
    environment:
      - POSTGRES_USER=langfuse
      - POSTGRES_PASSWORD=Ab123456
      - POSTGRES_PORT=langfuse
      - POSTGRES_PORT=5432
    ports:
      - "5434:5432"
    networks:
      - app-network
  clickhouse:
    extends:
      file: ./docker-compose.yml
      service: clickhouse
    environment:    
      - CLICKHOUSE_DB=langfuse
      - CLICKHOUSE_USER=langfuse
      - CLICKHOUSE_PASSWORD=Ab123456
    networks:
      - app-network

networks:
  app-network:
    driver: bridge